import { D1Database, KVNamespace, R2Bucket } from "@cloudflare/workers-types";

// This file is auto-generated by `wrangler types` and modified manually.
export interface Env {
  DB: D1Database;
  SESSION_KV: KVNamespace;
  BROADCAST_KV: KVNamespace;
  VERIFY_KV: KVNamespace;
  RECEIPTS_BUCKET: R2Bucket;
  AI: any; // Ai binding from Cloudflare
  APP_ENV: "development" | "production";
  APP_URL: string;
  CORS_ORIGIN: string;
}
